domain: dishajk.github.io
url: https://dishajk.github.io

collections:
  projects:
  resources:

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "fieldnote"
- scope:
    path: ""
  values:
    layout: "default"

exclude:
  - oldStuff